In [165]:
# importing numpy library 
import numpy as np 
import sympy as sp
  
# create numpy 2d-array 
a = np.array([[3, 2, 2], 
              [2, 3, -2]]) 
  
print(a)
print(a.T)

[[ 3  2  2]
 [ 2  3 -2]]
[[ 3  2]
 [ 2  3]
 [ 2 -2]]




![title](img/svd_ex1.jpeg)

In [98]:
aat = np.dot(a, a.T)
print(aat)
w, v = np.linalg.eig(aat) 
  
# printing eigen values 
print("Printing the Eigen values of the given square array:\n",  w) 
  
# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n",v)

[[17  8]
 [ 8 17]]
Printing the Eigen values of the given square array:
 [25.  9.]
Printing Right eigenvectors of the given square array:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


The characteristic polynomial is 
det(AAT − λI) = λ^2 − 34λ + 225 = (λ − 25)(λ − 9), so
the singular values are σ1 =√25 = 5 and σ2 =√9 = 3.

In [166]:
ata = np.dot(a.T, a)
print(ata)
b = np.identity(3, dtype = float)
print(b)
v1 = ata - 25*b
print(v1)

[[13 12  2]
 [12 13 -2]
 [ 2 -2  8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-12.  12.   2.]
 [ 12. -12.  -2.]
 [  2.  -2. -17.]]


In [34]:
v11 = sp.Matrix(v1).rref()
print(v11)

(Matrix([
[  1, -1.0,   0],
[0.0,  0.0,   1],
[0.0,  0.0, 0.0]]), (0, 2))


In [78]:
v111 = v11[0]
string_array = np.array(v111)
v111 = string_array.astype(np.float)
print(v111)

[[ 1. -1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [173]:
def row_echelon(A):
    """ Return Row Echelon Form of matrix A """

    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])


row_echelon(v111)

array([[ 1., -1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [80]:
print(v111.shape)
print(v111[0])


(3, 3)
[ 1. -1.  0.]


In [167]:
def unit_vector(v):
    return v / np.linalg.norm(v)
u = np.array([3, 6, 4])
print(u)
print(unit_vector(u))
v = np.array(v111[0])
print(v)

v1111 = unit_vector(v)
print(v1111)

[3 6 4]
[0.38411064 0.76822128 0.51214752]
[ 1. -1.  0.]
[ 0.70710678 -0.70710678  0.        ]


In [168]:
v2 = ata - 9*b
print(9*b)
print(v2)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]
[[ 4. 12.  2.]
 [12.  4. -2.]
 [ 2. -2. -1.]]


In [92]:
v22 = sp.Matrix(v2).rref()
print(v22)

(Matrix([
[1, 0, -0.25],
[0, 1,  0.25],
[0, 0,     0]]), (0, 1))


In [93]:
string_array = np.array(v22[0])
v222 = string_array.astype(np.float)
print(v222)

[[ 1.    0.   -0.25]
 [ 0.    1.    0.25]
 [ 0.    0.    0.  ]]


In [172]:
v2222 = np.array(v222[0])
v2222 = unit_vector(v2222)
print(v2222)

[ 0.9701425   0.         -0.24253563]


In [110]:
U = np.array([[ 0.70710678, 0.70710678],[ 0.70710678,- 0.70710678]])
S = np.array([[5,0,0],[0,3,0]])
V = np.array([[0.70710678,0.70710678,0],[0.24253563,-0.24253563,0.9701425],[0.666666666666667,-0.666666666666667,-0.333333333333333]])

![title](img/svd_ex2.jpeg)

In [155]:
b = np.matmul(U,S)
A = np.matmul(b,V)
print(A)

[[ 3.01449576  1.98550423  2.05798302]
 [ 1.98550423  3.01449576 -2.05798302]]


In [159]:
a = np.array([[3, 2, 2], 
              [2, 3, -2]]) 
  
U1, s1, V1T = np.linalg.svd(a)
print(U1)
print(s1)
print(V1T)

# create m x n D matrix
print(a.shape)
D = np.zeros(a.shape)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[5. 3.]
[[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]
(2, 3)


In [162]:
# populate D with n x n diagonal matrix

diagonal = np.diag(s1)
extra = np.array([[0],[0]])
diagonal = np.append(diagonal, extra, axis=1)

print(diagonal)

[[5. 0. 0.]
 [0. 3. 0.]]


In [163]:

b = np.matmul(U1,diagonal)
A = np.matmul(b,V1T)
print(A)

[[ 3.  2.  2.]
 [ 2.  3. -2.]]
